# Generated by Django 4.2.21 on 2025-05-15 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 22, 6, 7, 416037, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habit.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
