# Generated by Django 4.2.21 on 2025-05-15 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_start_date_habitlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='completed',
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 22, 41, 35, 513935, tzinfo=datetime.timezone.utc)),
        ),
    ]
