# Generated by Django 4.2.21 on 2025-05-16 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_remove_habitlog_completed_alter_habit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 19, 41, 31, 19400, tzinfo=datetime.timezone.utc)),
        ),
    ]
